# Generated by Django 3.2.6 on 2021-08-27 07:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SendEmail', '0004_alter_email_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 7, 39, 32, 244217, tzinfo=utc)),
        ),
    ]
