# Generated by Django 3.2.6 on 2021-08-27 01:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Michelin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 1, 2, 54, 14859, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 1, 2, 54, 15157, tzinfo=utc)),
        ),
    ]
