# Generated by Django 3.2.6 on 2021-08-27 02:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Michelin', '0003_auto_20210827_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 2, 18, 3, 220933, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Michelin.category'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 2, 18, 3, 221320, tzinfo=utc)),
        ),
    ]
