# Generated by Django 3.2.6 on 2021-08-27 07:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Michelin', '0004_auto_20210827_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 7, 29, 20, 190843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 7, 29, 20, 191132, tzinfo=utc)),
        ),
    ]
