# Generated by Django 3.2.6 on 2021-08-27 07:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Michelin', '0006_auto_20210827_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 7, 39, 32, 243213, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 7, 39, 32, 243557, tzinfo=utc)),
        ),
    ]
