# Generated by Django 3.2.6 on 2021-08-27 08:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Michelin', '0007_auto_20210827_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 8, 32, 25, 932038, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 8, 32, 25, 932387, tzinfo=utc)),
        ),
    ]
